### PR TITLE
Rename FmxImportingContext to FamixImportingContext.

### PR DESCRIPTION
**Pull request by ClotildeToullec**
This should fix the loading in new Moose images.
Sorry about that, I'll make sure it does not happen again.

### CODE REVIEW

**Comment by ClotildeToullec** [comment]
I don't get why 31 files are changed. Metadata?
The actual change is only in `FamixImportingContext`: its superclasse has been renamed.

**Comment by fuhrmanator** [comment]
Thank you, @ClotildeToullec. As for the 31 files that are changed, the MM in the master branch is not as clean as another in a fork on my repo, but this is the one my students used this semester. 

I should be able to do the rename on my own fork, so I appreciate you fixing this quickly. 

My course that uses Moose goes from Jan to mid-April typically, so stability of the latest Moose from that period is ideal. But it was cute that one of my students pointed out to me yesterday that it's called "Moose 10 development" so it's normal that things break.

**Comment by ClotildeToullec** [comment]
You will be glad to hear that I'm currently tagging moose 10 as stable! Changes will now occur in moose 11.

**Comment by fuhrmanator** [comment]
Of course, we'll be interested in the latest Moose, so the cycle will continue. 🤣 

One thing that was suggested to me was to make the contents of the Famix-TypeScript-Entities package entirely generated (I tried to do that on my fork at fuhrmanator), so that when things like renamings happen, it's easy to just load only that package and re-generate the entities. 

Software design tries to make things less dependent on change, as it's inevitable. As long as stuff in the Famix-TypeScript-Generator package doesn't break, it should be relatively easy for us to adapt in the future.

**Pull request merged**
